#!/usr/bin/env bash

# Using root to install all the packages
# And then switch to the target user to setup

if [ $EUID -ne 0 ]; then
  sudo ./getpackages.sh
else
  ./getpackages.sh
fi

./config.sh

# If script can reach here, simply return 0
exit 0
